django/motd/urls.py
from django.conf.urls import url
from motd.views import *

urlpatterns = [
    # /
    url(r'^$',PostLV.as_view(), name='index'),

    # /post/
    url(r'^$',PostLV.as_view(), name='index'),

    # /post/99/
    url(r'^post/(?P<pk>\d+)/$',PostDV.as_view(), name='post_detail'),

    # /tag/
    url(r'^tag/$',TagTV.as_view(), name='tag_cloud'),

    # /tag/tagname/
    url(r'^tag/(?P<tag>[^/]+(?u))/$', PostTOL.as_view(), name='tagged_object_list'),
]

django/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from mysite.views import HomeView

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),

    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^motd/', include('motd.urls', namespace='motd')),
]

django/motd/models.py
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible

from django.db import models
from django.core.urlresolvers import reverse
from tagging.fields import TagField

# Create your models here.

@python_2_unicode_compatible
class Post(models.Model):
    title = models.CharField('TITLE', max_length=50)
    content = models.TextField('CONTENT')
    create_date = models.DateTimeField('Create Date', auto_now_add=True)
    modify_date = models.DateTimeField('Modify Date', auto_now=True)
    tag = TagField()

    class Meta:
        verbose_name = 'post'
        verbose_name_plural = 'posts'
        ordering = ('-create_date',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('motd:post_detail', args=(self.id,))

django/motd/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, TemplateView

from motd.models import Post

from tagging.models import Tag, TaggedItem
from tagging.views import TaggedObjectList

# Create your views here.

class PostLV(ListView):
    model = Post
    template_name = 'motd\post_all.html'
    context_object_name = 'posts'
    paginate_by = 30

class PostDV(DetailView):
    model = Post

class TagTV(TemplateView):
    template_name = 'tagging/tagging_cloud.html'

class PostTOL(TaggedObjectList):
    model = Post
    template_name = 'tagging/tagging_post_list.html'

django/mysite/views.py
from django.views.generic.base import TemplateView

class HomeView(TemplateView):
    template_name = 'home.html'

django/motd/templates/motd/post_all.html
{% extends "base.html" %}
{% block title %}post_all.html{% endblock %}

{% block content %}
{% for post in posts %}
    <h2><a href = '{{  post.get_absolute_url }}'>{{ post.title }}</a></h2>
    {{ post.create_date|date:"N d, Y" }}
    <p>{{ post.content }}</p>
{% endfor %}

# <--무한스크롤-->
{% endblock %}

django/motd/templates/motd/post_detail.html
{% extends "base.html" %}

{% block title %}post_detail.html{% endblock %}

{% block content %}
<h2>{{ object.title }}</h2>
<p class="date">{{ object.create_date|date:"j F Y" }}</p>
    <br/>
<div>
    {{ object.content|linebreaks }}
</div>

<div>
    <b>Cosmetics: </b>
    {% load tagging_tags %}
    {% tags_for_object object as tags %}
    {% for tag in tags %}
    <a href="{% url 'motd:tagged_object_list' tag.name %}">{{ tag.name }}</a>
    {% endfor %}

    <a href="{% url 'motd:tag_cloud' %}"><i>CosmeticCloud</i></a>
</div>
{% endblock %}

django/motd/templates/tagging/tagging_cloud.html
{% extends "base.html" %}

{% block title %}tagging_cloud.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "tagging/tag.css" %}{% endblock %}

{% block content %}
<div class="tag-cloud">
    {% load tagging_tags %}
    {% tag_cloud_for_model motd.Post as tags with steps=6 min_count=1 distribution=log %}
    {% for tag in tags %}
    <span class="tag-{{ tag.font_size }}">
        <a href="{% url 'motd:tagged_object_list' tag.name %}">{{ tag.name }}</a>
    </span>
    {% endfor %}
</div>

{% endblock %}

django/motd/templates/tagging/tagging_post_list.html
{% extends "base.html" %}

{% block title %}tagging_post_list.html{% endblock %}

{% block content %}
<h2>{{ tag.name }}</h2>
{% for post in object_list %}

<a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
# post.title -> img로 바꿀 것
{% endfor %}

{% endblock %}

django/templates/base.html
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <title>{% block title %}ROCO{% endblock %}</title>
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static "css/base.css" %}" />
<link rel="stylesheet" type="text/css" href="{% block extrastyle %}{% endblock %}" />
</head>

<body>
<p>홈데스</p>
{% block content %}{% endblock %}

{% block footer %}{% endblock %}
</body>
</html>

django/templates/home.html
{% extends "base.html" %}

{% block title %}home.html{% endblock %}

{% block content %}
<div>This is content</div>
{% endblock content %}